// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisMinistritosAPI.Data;

#nullable disable

namespace MisMinistritosAPI.Migrations
{
    [DbContext(typeof(ContextDb))]
    partial class ContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.ClienteDbModel", b =>
                {
                    b.Property<string>("cedula")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("comboReferencia")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("correoElectronico")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("fechaNacimiento")
                        .HasColumnType("int");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("profesion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.HasKey("cedula");

                    b.ToTable("ClienteDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.FacturaDbModel", b =>
                {
                    b.Property<string>("facturaId")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("clienteCedula")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("clienteNombre")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("montoIVA")
                        .HasColumnType("decimal");

                    b.Property<decimal>("montoSubTotal")
                        .HasColumnType("decimal");

                    b.Property<decimal>("montoTotal")
                        .HasColumnType("decimal");

                    b.HasKey("facturaId");

                    b.ToTable("FacturaDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.ProductoDbModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ingreso")
                        .HasColumnType("int");

                    b.Property<int>("precioCompra")
                        .HasColumnType("int");

                    b.Property<string>("proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("proveedorDbModelcedula")
                        .HasColumnType("varchar(12)");

                    b.Property<int>("utilidad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("proveedorDbModelcedula");

                    b.ToTable("ProductoDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.ProveedorDbModel", b =>
                {
                    b.Property<string>("cedula")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("cedula");

                    b.ToTable("ProveedorDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.TourDbModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("diasTour")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("precioTour")
                        .HasColumnType("int");

                    b.Property<string>("proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("proveedorDbModelcedula")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("verImagen")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("id");

                    b.HasIndex("proveedorDbModelcedula");

                    b.ToTable("TourDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.VentaDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("FacturaDbModelfacturaId")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("cantidadProducto")
                        .HasColumnType("int");

                    b.Property<string>("descripcionDatoF")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("idDatoF")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("productoPrecio")
                        .HasColumnType("decimal");

                    b.Property<decimal>("totalProducto")
                        .HasColumnType("decimal");

                    b.HasKey("id");

                    b.HasIndex("FacturaDbModelfacturaId");

                    b.ToTable("VentaDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.ProductoDbModel", b =>
                {
                    b.HasOne("MisMinistritosAPI.Models.ModelDb.ProveedorDbModel", "proveedorDbModel")
                        .WithMany()
                        .HasForeignKey("proveedorDbModelcedula");

                    b.Navigation("proveedorDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.TourDbModel", b =>
                {
                    b.HasOne("MisMinistritosAPI.Models.ModelDb.ProveedorDbModel", "proveedorDbModel")
                        .WithMany()
                        .HasForeignKey("proveedorDbModelcedula");

                    b.Navigation("proveedorDbModel");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.VentaDbModel", b =>
                {
                    b.HasOne("MisMinistritosAPI.Models.ModelDb.FacturaDbModel", null)
                        .WithMany("productosFactura")
                        .HasForeignKey("FacturaDbModelfacturaId");
                });

            modelBuilder.Entity("MisMinistritosAPI.Models.ModelDb.FacturaDbModel", b =>
                {
                    b.Navigation("productosFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
